"""QA cross-cutting roundtrip gate (FU-15) — promoted from the PM merge-gate script.

G-17: producer→consumer alignment is proven by a measured roundtrip, not prose —
this drives the real CLI ``main()`` end-to-end over a fake docker client and
asserts the full seam: exit-code contract 0/1/2/3 (DoD-P2-07), spawn order
runner→SUT (G-19 supply order), scenario-sourced SUT image, runner env seam incl.
scenario-derived ROS_DISTRO/RMW_IMPLEMENTATION injection (FU-14) with no SUT env
leak (DoD-P2-03), GPU DeviceRequests runner-only, and network teardown.

G-20: the REAL docker module stays imported (so ``docker.types`` submodule
imports keep resolving); only the ``docker.from_env`` entrypoint is
monkeypatched per-test.

QA-owned cross-cutting test (decision 2026-06-25-tests-ownership) — implementation
teams do not edit this file.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import docker  # real module on purpose (G-20) — entrypoint patched per-test
from cv_infra.cli.main import main
from tests.test_supervisor_min import FakeClient

FIXTURE = Path(__file__).parent / "fixtures" / "nova_carter_warehouse_goal.yaml"
RUNNER_IMAGE = "cv-infra-runner:p2"
SUT_IMAGE = "carter-sut:p2"  # scenario-sourced (fixture sut.image_ref) — not a CLI arg


@pytest.fixture()
def spawned(monkeypatch):
    """Patch only the docker entrypoint (G-20); collect every client handed out."""
    clients: list[FakeClient] = []

    def fake_from_env():
        client = FakeClient()
        clients.append(client)
        return client

    monkeypatch.setattr(docker, "from_env", fake_from_env)
    return clients


def run_case(out_dir: Path, job_id: str, scenario: Path, pre_verdict: str | None = None) -> int:
    """Invoke the real CLI; optionally pre-write the result the fake runner would emit."""
    if pre_verdict is not None:
        result = out_dir / job_id / "result" / "result.json"
        result.parent.mkdir(parents=True, exist_ok=True)
        result.write_text(json.dumps({"job_id": job_id, "verdict": pre_verdict}), encoding="utf-8")
    return main(
        [
            "run",
            str(scenario),
            "--runner-image",
            RUNNER_IMAGE,
            "--out-dir",
            str(out_dir),
            "--job-id",
            job_id,
        ]
    )


@pytest.mark.parametrize(
    ("pre_verdict", "expected_exit"),
    [("pass", 0), ("fail", 1), (None, 3)],  # None = runner produced no result → infra 3
)
def test_exit_code_contract_docker_paths(tmp_path, spawned, pre_verdict, expected_exit):
    assert run_case(tmp_path, f"rt-{expected_exit}", FIXTURE, pre_verdict) == expected_exit
    assert len([c for c in spawned if c.run_calls]) == 1  # docker path actually exercised


def test_bad_input_exits_2_without_spawning(tmp_path, spawned):
    bad = tmp_path / "bad.yaml"
    bad.write_text("bad_key: 1\nscenario: {}\n", encoding="utf-8")
    assert run_case(tmp_path, "rt-bad", bad) == 2
    assert [c for c in spawned if c.run_calls] == []  # rejected before any docker spawn


def test_roundtrip_seam_order_env_gpu_and_teardown(tmp_path, spawned):
    assert run_case(tmp_path, "rt-seam", FIXTURE, pre_verdict="pass") == 0
    (client,) = [c for c in spawned if c.run_calls]

    # spawn order + scenario-sourced SUT image (runner first — clock source, G-19)
    assert [image for image, _ in client.run_calls] == [RUNNER_IMAGE, SUT_IMAGE]
    assert client.network is not None and client.network.remove_calls >= 1

    runner_env = client.run_calls[0][1].get("environment", {})
    sut_env = client.run_calls[1][1].get("environment", {})
    assert "JOB_SPEC" in runner_env and "RESULT_OUT" in runner_env
    assert runner_env.get("ROS_DOMAIN_ID") == sut_env.get("ROS_DOMAIN_ID")

    # FU-14: scenario-derived injection (fixture declares jazzy / rmw_fastrtps_cpp)
    assert runner_env.get("ROS_DISTRO") == "jazzy"
    assert runner_env.get("RMW_IMPLEMENTATION") == "rmw_fastrtps_cpp"
    assert "ROS_DISTRO" not in sut_env  # SUT blackbox — no env leak (DoD-P2-03)

    # GPU DeviceRequests runner-only
    runner_dr = client.run_calls[0][1].get("device_requests")
    assert runner_dr and len(runner_dr) == 1
    assert client.run_calls[1][1].get("device_requests") in (None, [])
