"""QA fixture-canonical drift guard — bind the platform fixture's
``acceptance_criteria`` params to the keys the oracles actually read.

Context (G-17 drift class): the platform keeps a COPY of the consumer's canonical
scenario because boundary rule 3 forbids referencing the consumer repo by relative
path. A stale copy (cycle-3 draft) carried ``goal_tolerance_m: 0.5``, which the
oracle never reads: ``criteria_view`` merges each criterion's ``params`` as a free
dict, so an unread key is silently swallowed and the oracle falls back to its
default (0.25 m). These asserts fail CI the moment the fixture drifts from what the
oracle reads — WITHOUT reading the consumer repo (in-repo assertion only; the
cross-repo diff is the PM merge-gate's job).

The allowed key set is PULLED FROM the oracle source (the ``read_field(criteria,
"...")`` call sites), never retyped — rename an oracle key and this guard fails
until the fixture is re-synced. The one retyped literal (``position_tolerance_m``)
is itself cross-checked against the oracle's read set below.

QA-owned cross-cutting test (decision 2026-06-25-tests-ownership) — implementation
teams do not edit this file.
"""

from __future__ import annotations

import importlib
import inspect
import re
from pathlib import Path

import yaml

# P3 cycle-2 re-wire (M8 task p3c2-cli-loader, minimal): the CLI transform is
# now loader-fed — ``load_request`` (M1 6-stage gate) + ``_job_spec_from_request``
# replace the retired ``_scenario_doc_to_job_spec``. Detection power preserved
# (same fixture -> REAL CLI wire -> runner parse -> criteria_view -> oracle
# validator), and the fixture now additionally passes the full admit gate.
from cv_infra.cli.main import _job_spec_from_request
from cv_infra.contract.loader import load_request
from cv_infra.contract.models import VerificationRequest
from cv_infra.oracles.no_collision import NoCollisionOracle
from cv_infra.runner.main import build_oracles, criteria_view

FIXTURE = Path(__file__).parent / "fixtures" / "nova_carter_warehouse_goal.yaml"

# Every oracle the engine BINDS -> its source module, so the param allow-list is
# derived from the SAME oracles the runner runs (build_oracles), not a hand-kept
# path list. If the engine swaps an oracle, its read set follows.
_ORACLE_MODULES = {o.name: importlib.import_module(type(o).__module__) for o in build_oracles()}

# ``read_field(criteria, "<key>", ...)`` call sites = the criteria keys an oracle
# consumes. Regex, not AST, on purpose (karpathy: a few asserts, not a framework).
_READ_FIELD = re.compile(r"""read_field\(\s*criteria\s*,\s*["'](\w+)["']""")


def _keys_oracle_reads(oracle_name: str) -> set[str]:
    """Keys ``oracle_name`` reads from criteria, parsed from its module source."""
    return set(_READ_FIELD.findall(inspect.getsource(_ORACLE_MODULES[oracle_name])))


def _fixture_doc() -> dict:
    return yaml.safe_load(FIXTURE.read_text(encoding="utf-8"))


def _params(oracle_name: str) -> dict:
    (crit,) = [c for c in _fixture_doc()["acceptance_criteria"] if c["oracle"] == oracle_name]
    return crit.get("params") or {}


def test_reached_goal_params_are_all_read_no_silent_ignore():
    """Silent-ignore guard (requirement 2). Every key under ``reached_goal.params``
    must be a key the reached_goal oracle actually reads. The cycle-3 draft
    ``goal_tolerance_m`` is NOT read -> ``criteria_view`` swallowed it -> the oracle
    applied its 0.25 m default instead of the measured tolerance. Any unread param
    key fails here (this is the real root cause of the silent 0.5 -> 0.25)."""
    reads = _keys_oracle_reads("reached_goal")
    unread = set(_params("reached_goal")) - reads
    assert not unread, (
        f"reached_goal.params has key(s) the oracle never reads {sorted(unread)} "
        f"-> silently ignored by criteria_view. Oracle reads: {sorted(reads)}"
    )


def test_reached_goal_carries_the_oracle_canonical_tolerance_key():
    """Requirement 1 (positive form). The fixture must actually CARRY
    ``position_tolerance_m`` (the oracle-canonical key) so the measured value is
    applied rather than the default — an empty params dict would pass the
    silent-ignore guard yet still fall back to 0.25 m. The literal is cross-checked
    against the oracle's own read set, so an oracle rename breaks this line too."""
    reads = _keys_oracle_reads("reached_goal")
    assert "position_tolerance_m" in reads  # the canonical key, per the oracle source
    assert "position_tolerance_m" in _params("reached_goal")  # ...carried by the fixture


def test_no_collision_params_are_all_read_no_silent_ignore():
    """Silent-ignore guard (requirement 2) for the no_collision criterion."""
    reads = _keys_oracle_reads("no_collision")
    unread = set(_params("no_collision")) - reads
    assert not unread, (
        f"no_collision.params has key(s) the oracle never reads {sorted(unread)}. "
        f"Oracle reads: {sorted(reads)}"
    )


def test_fixture_satisfies_no_collision_bind_precondition():
    """Bind precondition (requirement 3). Drive the fixture through the REAL CLI
    scenario->JOB_SPEC transform + ``criteria_view``, then let no_collision's OWN
    validator judge it. If ``chassis_path`` were absent (as in the cycle-3 draft's
    ``params: {}``), ``validate_params`` raises and ``telemetry.bind()`` would raise
    on a real runner (P2-13 precondition). No requirement is retyped — the oracle
    code decides what is required (chassis_path, D-E/R7)."""
    job_spec = _job_spec_from_request(load_request(FIXTURE).request, "fixture-guard")
    view = criteria_view(VerificationRequest.from_dict(job_spec))
    NoCollisionOracle().validate_params(view)  # raises ValueError if chassis_path missing
    assert view.get("chassis_path"), "criteria_view is missing chassis_path after merge"
