"""QA cross-cutting guard — every document the PLATFORM ITSELF supplies must
(a) satisfy the runner's UNCONDITIONAL preconditions and (b) ride the REAL M1
admit path. Parameterized over a DOCUMENT-SOURCE REGISTRY (G-70).

WHY PARAMETERIZED (the measured failure, p5c15): the same class of defect —
a self-supplied request that declares ``reached_goal`` ALONE, so the runner's
unconditional ``telemetry.bind()`` raises before the readiness barrier — had a
guard already (``test_fixture_canonical_guard``), and that guard looked at
``tests/fixtures/*.yaml`` ONLY. When a SECOND document source appeared (the
built-in self-test stub, ``cv_infra/orchestrator/selftest.py``) the defect came
back untouched. A per-source hand-written guard re-buys the same lesson every
time an input source is added; a registry makes the next source declare itself
or fail ``test_every_document_source_is_registered``.

WHY (b) IS HERE AT ALL: p5c15 also measured that NOTHING locked "the submission
actually traverses M1 admit" — a bypass branch could be planted and the whole
suite stayed green. (a) alone is therefore not enough: a document can satisfy
every precondition and still be admitted by a shortcut that proves nothing about
the path a consumer request takes (``REQ-SELFTEST-002`` 경로 동일성).

HOW EACH PROPERTY IS MADE NON-VACUOUS (G-35) — both controls live in-file, so
every registered source carries its own proof of sensitivity:
  * (a) the same document with its ``no_collision`` criterion stripped MUST fail
    the replay (that is the exact p5c15 shape);
  * (b) the same document with one poison key MUST be refused BY NAME, while the
    clean document MUST be accepted through the same production path.

NOT RETYPED: the (a) predicate is the runner's own code — this file builds the
sampler exactly as ``runner/main.py`` does and calls the REAL
``PhysicsTelemetrySampler.bind``; the platform's own ``RuntimeError`` is the
failure signal. Reaching the GPU-only ``omni`` import means the precondition held.

QA-owned cross-cutting test (decision 2026-06-25-tests-ownership) — implementation
teams do not edit this file.
"""

from __future__ import annotations

import io
import json
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import pytest
import yaml
from fastapi.testclient import TestClient

from cv_infra.cli import batch
from cv_infra.contract.errors import ContractError
from cv_infra.contract.loader import load_request
from cv_infra.orchestrator import api
from cv_infra.orchestrator.models import Job, JobResult, JobState, Verdict
from cv_infra.orchestrator.selftest import SUT_IMAGE_ENV, build_self_test_submission
from cv_infra.orchestrator.store import Store
from cv_infra.runner.evaluate import read_field
from cv_infra.runner.main import criteria_view
from cv_infra.runner.telemetry import PhysicsTelemetrySampler

_REPO = Path(__file__).resolve().parents[1]
_FIXTURES = Path(__file__).parent / "fixtures"

#: A PLATFORM-internal stub SUT handle for CPU tests (never a consumer image).
_STUB_ENV = {SUT_IMAGE_ENV: "cv-infra-selftest-stub:test"}

#: A key no request model accepts. Only the M1 admit gate (``extra="forbid"``)
#: rejects it, and the rejection NAMES it — so seeing the name in the refusal
#: proves the gate ran, not that something generic failed.
_POISON_KEY = "__qa_admit_probe__"


class _PassRunner:
    """Fake runner seam: every job completes PASS (CPU, no docker/GPU)."""

    def run(self, job: Job) -> JobResult:
        return JobResult(job=job, state=JobState.COMPLETED, verdict=Verdict.PASS)


def _post_envelope(body: dict, workdir: Path) -> str:
    """POST an envelope to the REAL app; 'accepted' or 'rejected: <detail>'."""
    workdir.mkdir(parents=True, exist_ok=True)
    with Store(workdir / "cv.sqlite3") as store:
        with TestClient(api.create_app(store, _PassRunner(), k=1)) as client:
            response = client.post("/envelopes", json=body)
    if response.status_code == 202:
        return "accepted"
    return f"rejected: HTTP {response.status_code} {response.text}"


# --------------------------------------------------------------------------- #
# The registry: one entry per document source the PLATFORM itself supplies.
# --------------------------------------------------------------------------- #
def _fixture_document() -> dict:
    return yaml.safe_load((_FIXTURES / "nova_carter_warehouse_goal.yaml").read_text("utf-8"))


def _submit_fixture(document: dict, workdir: Path) -> str:
    """The production path for a scenario FILE: ``cv-infra submit <path>``.

    ``_synthesize_envelope`` runs the client-side M1 gate and ``_wire_body``
    builds the POST body — both production code, no re-implementation here.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    path = workdir / "scenario.yaml"
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    try:
        envelope = batch._synthesize_envelope([str(path)])
    except ContractError as err:
        return f"rejected: client-side M1 gate — {err}"
    return _post_envelope(batch._wire_body(envelope), workdir)


def _stub_document() -> dict:
    (document,) = build_self_test_submission(environ=_STUB_ENV).body["requests"]
    return document


def _submit_stub(document: dict, workdir: Path) -> str:
    """The production path for the built-in stub: ``cv-infra selftest``.

    The ENVELOPE (size-1, both markers) is built by production code; only the
    request document is substituted, which is what the poison probe varies.
    """
    body = build_self_test_submission(environ=_STUB_ENV).body
    return _post_envelope({**body, "requests": [document]}, workdir)


@dataclass(frozen=True)
class _Source:
    """One document source: where it comes from and how production submits it."""

    id: str
    owner: str  # repo-relative path of the module/file that OWNS the document
    document: Callable[[], dict]
    submit: Callable[[dict, Path], str]


_SOURCES = [
    _Source(
        id="fixture-yaml",
        owner="tests/fixtures/nova_carter_warehouse_goal.yaml",
        document=_fixture_document,
        submit=_submit_fixture,
    ),
    _Source(
        id="built-in-stub",
        owner="cv_infra/orchestrator/selftest.py",
        document=_stub_document,
        submit=_submit_stub,
    ),
]

#: Every place in ``cv_infra`` that writes an ``"acceptance_criteria":`` dict key,
#: classified. ``document-source`` = it AUTHORS a request document and therefore
#: needs a registry entry above. ``projection-of-admitted`` = it re-renders a
#: request that ALREADY passed the admit gate (JOB_SPEC / canonical echo), so the
#: properties below were established upstream. A NEW site fails the registry test
#: until someone classifies it — that is the G-70 trigger.
_CONSTRUCTION_SITES = {
    "cv_infra/orchestrator/selftest.py": "document-source",
    "cv_infra/contract/loader.py": "projection-of-admitted",
    # p8c1: the JOB_SPEC projection that used to be DUPLICATED in
    # ``cv_infra/cli/main.py`` and ``cv_infra/orchestrator/api.py`` is now a
    # single definition here; both planes call it and author no dict of their
    # own, so the two entries are gone and this one replaces them (the guard's
    # own instruction — same classification, one site instead of two).
    "cv_infra/contract/job_spec.py": "projection-of-admitted",
}


def _discovered_construction_sites() -> set[str]:
    """Files under ``cv_infra`` that build a dict with an ``acceptance_criteria`` key."""
    pattern = re.compile(r'"acceptance_criteria"\s*:')
    return {
        str(path.relative_to(_REPO))
        for path in sorted((_REPO / "cv_infra").rglob("*.py"))
        if pattern.search(path.read_text(encoding="utf-8"))
    }


def _fixture_documents_on_disk() -> set[str]:
    """Fixture YAMLs that are request documents (they declare acceptance criteria)."""
    return {
        str(path.relative_to(_REPO))
        for path in sorted(_FIXTURES.glob("*.yaml"))
        if "acceptance_criteria" in path.read_text(encoding="utf-8")
    }


def test_every_document_source_is_registered():
    """The registry must cover every source the repo actually has (G-70).

    Two halves: the in-code authors (classified construction sites) and the
    on-disk fixture documents. Add a source, and this reddens until it is
    registered above — which is the whole point of parameterizing.
    """
    discovered = _discovered_construction_sites()
    assert discovered == set(_CONSTRUCTION_SITES), (
        "cv_infra document-construction sites changed — classify the new one(s) as "
        "'document-source' (then register it in _SOURCES) or 'projection-of-admitted'. "
        f"new={sorted(discovered - set(_CONSTRUCTION_SITES))} "
        f"gone={sorted(set(_CONSTRUCTION_SITES) - discovered)}"
    )
    registered = {source.owner for source in _SOURCES}
    authors = {path for path, kind in _CONSTRUCTION_SITES.items() if kind == "document-source"}
    assert authors <= registered, f"unregistered document author(s): {sorted(authors - registered)}"
    assert _fixture_documents_on_disk() <= registered, (
        "unregistered fixture request document(s): "
        f"{sorted(_fixture_documents_on_disk() - registered)}"
    )


# --------------------------------------------------------------------------- #
# (a) the runner's UNCONDITIONAL preconditions
# --------------------------------------------------------------------------- #
def _admitted(document: dict):
    """The document through the REAL M1 6-stage gate -> the typed request."""
    return load_request(
        io.StringIO(json.dumps(document, indent=2, sort_keys=True)),
        source_path="document-source-guard",
    ).request


def _replay_runner_unconditional_bind(document: dict) -> str | None:
    """Replay ``runner/main.py``'s UNCONDITIONAL step-2->3 wiring on a document.

    The runner builds ``PhysicsTelemetrySampler`` and registers ``sampler.bind``
    as a pre-reset hook for EVERY job — it never asks whether a collision
    criterion was declared — and ``bind`` validates its precondition BEFORE any
    Isaac import. So calling the real ``bind`` here reproduces the live failure on
    a CPU box: ``RuntimeError`` = precondition unmet (returned as the reason);
    ``ImportError`` = precondition held and execution reached the GPU-only import.
    """
    view = criteria_view(_admitted(document))
    sampler = PhysicsTelemetrySampler(  # main.py's construction, verbatim
        read_field(view, "chassis_path", ""),
        read_field(view, "collision_excluded_paths", []) or [],
    )
    try:
        sampler.bind(object())
    except ImportError:
        return None  # past the precondition, died on the GPU-only import
    except RuntimeError as exc:
        return str(exc)
    raise AssertionError(
        "telemetry.bind() no longer reaches its GPU-only import — this probe is stale"
    )


@pytest.mark.parametrize("source", _SOURCES, ids=lambda s: s.id)
def test_document_satisfies_the_runner_unconditional_bind_precondition(source):
    """★ p5c15 라이브 차단 회귀, now per SOURCE."""
    unmet = _replay_runner_unconditional_bind(source.document())
    assert unmet is None, f"{source.owner} would raise in telemetry.bind(): {unmet}"

    # 비공허 대조 (G-35): the exact p5c15 shape — drop the no_collision criterion
    # (the only home of chassis_path) and the SAME replay must now fail.
    stripped = {
        **source.document(),
        "acceptance_criteria": [
            c for c in source.document()["acceptance_criteria"] if c["oracle"] != "no_collision"
        ],
    }
    assert stripped["acceptance_criteria"], f"{source.owner} declares no_collision only"
    assert (
        _replay_runner_unconditional_bind(stripped) is not None
    ), "the probe is insensitive to the measured defect — it would pass either way"


# --------------------------------------------------------------------------- #
# (b) the REAL admit path
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("source", _SOURCES, ids=lambda s: s.id)
def test_document_is_submitted_through_the_real_admit_gate(source, tmp_path):
    """A bypass branch would let the poisoned document through — this reddens.

    The clean leg keeps the poison leg honest: a path that refuses EVERYTHING
    would satisfy the refusal assert while proving nothing.
    """
    assert source.submit(source.document(), tmp_path / "clean") == "accepted"

    poisoned = source.submit({**source.document(), _POISON_KEY: True}, tmp_path / "poison")
    assert poisoned.startswith("rejected"), (
        f"{source.owner}: a document with an unknown key was ACCEPTED — the M1 admit "
        f"gate did not run on this submission path ({poisoned})"
    )
    assert _POISON_KEY in poisoned, (
        f"{source.owner}: refused, but not BY the admit gate (the refusal never names "
        f"the offending key): {poisoned}"
    )
